### PR TITLE
Add more flight filters

### PR DESCRIPTION
**Pull request by Dlunhappy226**
Added registration and aircraft type to get flight. Also changing the "airline" parameters to "callsign" since the flightradar API has changed.

### CODE REVIEW

**Comment by JeanExtreme002** [comment]
I didn't understand why you changed `airline` to `callsign`. The param `airline` still works.

**Comment by Dlunhappy226** [comment]
Changed back to `airline` param.

> I didn't understand why you changed `airline` to `callsign`. The param `airline` still works.

**Comment by JeanExtreme002** [comment]
Could you please give me an example of `aircraft_type` so I can understand what that parameter is about?

**Comment by Dlunhappy226** [comment]
Like B734 for Boeing 737-400

**Comment by JeanExtreme002** [comment]
OK. Thank you very much for your contribution!! :smile:

**Pull request merged**
